### ISSUE TITLE
Open Src Contributions

### ISSUE THREAD

**Issue by DIvkov575** [KevinArce/Scikit-Learn#1]
GitHub recommended this as open-src, and I'm not sure if you want contributions but here I am.
I had a similar project, so let me know if you would appreciate the help.

some of the possible features I had in mind in addition to creating snippets were creating visualization representations for each predictor and adding docs

**Comment by KevinArce** [comment]
Hi Dima! 
Yes, I would love people to contribute and add to this repo, so feel free to suggest, make changes and so on. 
And prior to continue, thank you so much for the interaction.

**Comment by KevinArce** [comment]
I just added you as a contributor Dima 🤠👍

**Comment by DIvkov575** [comment]
thank you
