### ISSUE TITLE
Reorganizing-files

### ISSUE THREAD

**Issue by DIvkov575** [KevinArce/Scikit-Learn#7]
Proposed organization

Dir 1 -  'vanilla' examples - organized in sub/directories the same way imports would be in the original lib
Dir 2 - 'Compound' Examples - examples that may depend on multiple predictors or other ie.  Hyper-parameter tuning

**Comment by DIvkov575** [comment]
what are your thoughts on this?

**Comment by KevinArce** [comment]
I like the plan! That would make the repository more organized than it is.

**Comment by DIvkov575** [comment]
I feel that there are too many overlapping imports from different 'categories'. Ill want to think of a different organization format.
